export const FETCH_LEADERBOARD_URL = process.env.REACT_APP_FETCH_LEADERBOARD_URL;
export const CREATE_LEADERBOARD_URL = process.env.REACT_APP_CREATE_LEADERBOARD_URL;
export const START_GAME_URL = process.env.REACT_APP_START_GAME_URL;
